name: Build Executables
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install pyinstaller pillow customtkinter cryptography argon2-cffi pycryptodome
      
    - name: Build EXE with Custom Icon
      run: pyinstaller --noconfirm --onedir --windowed --clean --icon="icon.ico" --name "Aegis_Crypto" main.py
      
    - name: Upload Aegis_Crypto Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Aegis_Crypto-Windows
        path: dist/
